### PR TITLE
Merge docker for when we use DigitalOcean

### PR DESCRIPTION
**Pull request by jyn514**

### CODE REVIEW

**Comment by jyn514** [comment]
Can't get docker to work locally; everything looks fine but laptop doesn't accept connections on port 5000. Want to fix that before we merge.

```bash
joshua@debian-thinkpad:~/Programming/web/cybersecSite$ docker run -it cybersite &
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
joshua@debian-thinkpad:~/Programming/web/cybersecSite$ telnet localhost 5000
Trying ::1...
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
```

**Comment by clayscode** [comment]
Did you cd into the directory and run docker-compose up?

**Comment by jyn514** [comment]
Whoops, used plain docker. Here's what I get with docker-compose:

```bash
joshua@debian-thinkpad:~/Documents/Programming/web/cybersecSite$ docker-compose up
Starting cybersecsite_web_1
Attaching to cybersecsite_web_1
web_1  |  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
joshua@debian-thinkpad:~/Documents/Programming/web/cybersecSite$ telnet localhost 5000
Trying ::1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.
```

This is the same thing I get with `docker run -it -p 5000:5000 cybersite`

**Comment by jyn514** [comment]
Looks to be working now. Merging it in.

I did have to run `docker-compose build` every time the app changed, we could use the [`volumes`](https://docs.docker.com/compose/overview/) feature to avoid that.

**Pull request merged**
